remote_theme: pages-themes/minimal@v0.2.0
title: Lung Nodule Segmentation
description: A research project exploring the effects of data augmention on the LIDC dataset.
show_downloads: false
github:
  is_project_page: false
plugins:
- jekyll-remote-theme
