remote_theme: pages-themes/minimal@v0.2.0
title: Data Augmentation for Lung Nodule Segmentatoin
description: A research project by Kevin Zhang, Tanush Yadav, and Marius Rakickas for our CSE 493G1: Deep Learning class.
plugins:
- jekyll-remote-theme
